In [21]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_csv('OnlineRetail.csv')

In [23]:
df.head()

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

    InvoiceDate  UnitPrice  CustomerID         Country  
0  12/1/10 8:26       2.55     17850.0  United Kingdom  
1  12/1/10 8:26       3.39     17850.0  United Kingdom  
2  12/1/10 8:26       2.75     17850.0  United Kingdom  
3  12/1/10 8:26       3.39     17850.0  United Kingdom  
4  12/1/10 8:26       3.39     17850.0  United Kingdom

In [24]:
df.apply(lambda x: len(x.unique()))

InvoiceNo      12468
StockCode       3645
Description     3618
Quantity         477
InvoiceDate    11240
UnitPrice       1053
CustomerID      2975
Country           38
dtype: int64

In [25]:
new = df.drop(['InvoiceNo', 'StockCode',  'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country'],axis=1)

In [26]:
q = new['Description'].value_counts()
q

WHITE HANGING HEART T-LIGHT HOLDER     1319
REGENCY CAKESTAND 3 TIER               1251
JUMBO BAG RED RETROSPOT                1023
PARTY BUNTING                           985
LUNCH BAG RED RETROSPOT                 807
PACK OF 72 RETROSPOT CAKE CASES         754
ASSORTED COLOUR BIRD ORNAMENT           710
SET OF 3 CAKE TINS PANTRY DESIGN        703
JAM MAKING SET WITH JARS                697
NATURAL SLATE HEART CHALKBOARD          685
HEART OF WICKER SMALL                   651
JUMBO BAG PINK POLKADOT                 619
GREEN REGENCY TEACUP AND SAUCER         618
ROSES REGENCY TEACUP AND SAUCER         617
JUMBO STORAGE BAG SUKI                  616
JAM MAKING SET PRINTED                  612
SMALL POPCORN HOLDER                    607
VICTORIAN GLASS HANGING T-LIGHT         607
JUMBO SHOPPER VINTAGE RED PAISLEY       604
RECIPE BOX PANTRY YELLOW DESIGN         600
SET OF 6 SPICE TINS PANTRY DESIGN       593
WOODEN PICTURE FRAME WHITE FINISH       592
SET/20 RED RETROSPOT PAPER NAPKI

In [29]:
new.head(2)

Description  Quantity
0  WHITE HANGING HEART T-LIGHT HOLDER         6
1                 WHITE METAL LANTERN         6

In [30]:
s = pd.DataFrame(q)
s = s[s>610]

In [31]:
s = s.dropna()
s

Description
WHITE HANGING HEART T-LIGHT HOLDER       1319.0
REGENCY CAKESTAND 3 TIER                 1251.0
JUMBO BAG RED RETROSPOT                  1023.0
PARTY BUNTING                             985.0
LUNCH BAG RED RETROSPOT                   807.0
PACK OF 72 RETROSPOT CAKE CASES           754.0
ASSORTED COLOUR BIRD ORNAMENT             710.0
SET OF 3 CAKE TINS PANTRY DESIGN          703.0
JAM MAKING SET WITH JARS                  697.0
NATURAL SLATE HEART CHALKBOARD            685.0
HEART OF WICKER SMALL                     651.0
JUMBO BAG PINK POLKADOT                   619.0
GREEN REGENCY TEACUP AND SAUCER           618.0
ROSES REGENCY TEACUP AND SAUCER           617.0
JUMBO STORAGE BAG SUKI                    616.0
JAM MAKING SET PRINTED                    612.0

In [32]:
qqq = s['Description']

In [33]:
len(qqq)

16

In [34]:
arr = np.array(qqq)

In [35]:
alll = sum(qqq)

In [36]:
alll

12667.0

In [37]:
freq = arr/alll
cov = [ arr/i for i in arr] #Confidence

In [39]:
for i in qqq:
    freq = np.append(freq,i/alll)
    temp = []
    for j in qqq:
        temp.append(j/i)
    cov.append(temp)        

In [40]:
freq

array([0.10412884, 0.09876056, 0.08076103, 0.07776111, 0.06370885,
       0.05952475, 0.05605116, 0.05549854, 0.05502487, 0.05407752,
       0.05139338, 0.04886714, 0.04878819, 0.04870924, 0.0486303 ,
       0.04831452, 0.10412884, 0.09876056, 0.08076103, 0.07776111,
       0.06370885, 0.05952475, 0.05605116, 0.05549854, 0.05502487,
       0.05407752, 0.05139338, 0.04886714, 0.04878819, 0.04870924,
       0.0486303 , 0.04831452])

In [42]:
cov #Confidence

[array([1.        , 0.94844579, 0.77558757, 0.74677786, 0.61182714,
        0.57164519, 0.53828658, 0.53297953, 0.52843063, 0.51933283,
        0.49355572, 0.46929492, 0.46853677, 0.46777862, 0.46702047,
        0.46398787]),
 array([1.05435651, 1.        , 0.8177458 , 0.7873701 , 0.64508393,
        0.60271783, 0.56754596, 0.56195044, 0.55715428, 0.54756195,
        0.52038369, 0.49480416, 0.4940048 , 0.49320544, 0.49240608,
        0.48920863]),
 array([1.28934506, 1.2228739 , 1.        , 0.96285435, 0.7888563 ,
        0.7370479 , 0.69403715, 0.68719453, 0.68132942, 0.66959922,
        0.63636364, 0.60508309, 0.60410557, 0.60312805, 0.60215054,
        0.59824047]),
 array([1.33908629, 1.27005076, 1.03857868, 1.        , 0.81928934,
        0.76548223, 0.72081218, 0.71370558, 0.70761421, 0.69543147,
        0.66091371, 0.6284264 , 0.62741117, 0.62639594, 0.62538071,
        0.6213198 ]),
 array([1.63444857, 1.55018587, 1.26765799, 1.22057001, 1.        ,
        0.93432466, 0.879801